### ISSUE TITLE
Style not loading

### ISSUE THREAD

**Issue by trackermb** [delzear/hass-formulaoneapi#1]
Hi, let me start by saying love this add-on and cant waiting for future features.  Im having an issue with the current code have copied and pasted it and the data is pulling perfectly but the font isn't changing on the next race and the tables aren't showing correctly for driver and contractor standing I have attached screenshots. I think I might not have a style or integration  that you are using, to be honest I'm pretty new to all this.

Hopefully you can point me in the right direction 
Thanks
Mark 
<img width="1596" alt="Screenshot 2021-08-11 at 00 02 01" src="https://user-images.githubusercontent.com/7849892/128945874-21b0153e-6018-4d6c-aa49-4a98b55d3f91.png">
<img width="1104" alt="Screenshot 2021-08-11 at 00 02 35" src="https://user-images.githubusercontent.com/7849892/128945878-07e454e8-faf9-4ac5-b167-546bb41523b4.png">
<img width="1107" alt="Screenshot 2021-08-11 at 00 02 52" src="https://user-images.githubusercontent.com/7849892/128945881-f319b228-762c-4505-864f-416e9e6a260c.png">

**Comment by delzear** [comment]
For the font, it is copyrighted by Formula One and I can't distribute it. What I did is download the font files off there website and created the file "font.css" in the "/config/www/fonts" folder and added the font file in the same folder. I then add a ressource in Configuration > Dashboard > Ressources.

font.css
`@font-face {
	font-family: 'FormulaOne';
    src: url(/local/fonts/Formula1-Regular_web.woff2)  format('woff2');
}`
![image](https://user-images.githubusercontent.com/727891/129021634-e150d73c-80d8-4ffe-8d08-dde9c918e1ac.png)
![image](https://user-images.githubusercontent.com/727891/129021703-58bc401b-02cf-49ac-9b12-b7dcd544a0ed.png)

For the table, for some reason the template engine will not render correctly if the "<tr>"is not on the same line as the "for"
`{% for driver in states.sensor.formula_one_sensor.attributes.drivers %} <tr>`
and
`{% for driver in states.sensor.formula_one_sensor.attributes.constructors %} <tr>`

**Comment by trackermb** [comment]
Thanks, got the tables to work perfectly. However wasn't able to get the font sorted got an F1 font added it to www/fonts/ and added the resource and changed the card to match the font name but still no joy.  Did notice there is a warning symbol beside the font.css entries line 1 and 2. 

Can you think of anything I may have missed

Thanks again 

<img width="1488" alt="Screenshot 2021-08-12 at 00 33 14" src="https://user-images.githubusercontent.com/7849892/129116812-2fbdb083-0465-4334-a9ef-240a5d437e7a.png">
