### ISSUE TITLE
Log warnings and memory use. 

### ISSUE THREAD

**Issue by Jurgenn22** [delzear/hass-formulaoneapi#12]
@delzear 
The sensor is causing a lot of warnings in the logs, every  minute a warning. And the memory usage is running above 75% all the time due to this sensor. is there anything to do? thanks in advance!

`2021-10-28 13:13:33 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.formula_one_sensor is taking over 10 seconds`

**Comment by delzear** [comment]
Do you still have this issue?

**Comment by Jurgenn22** [comment]
@delzear No everything works perfect. Thank you!

**Comment by delzear** [comment]
Thanks!
