### ISSUE TITLE
Edit Time

### ISSUE THREAD

**Issue by ostracizado** [delzear/hass-formulaoneapi#19]
Is there a way to change the time present, from: "00:00:00Z", to simply show hour & minutes ("00:00") - only?

**Comment by huizebruin** [comment]
> Is there a way to change the time present, from: "00:00:00Z", to simply show hour & minutes ("00:00") - only?

Yes there is.

Woud you try this one ?
````
 {% set nr = states.sensor.formula_one_sensor.attributes.next_race  %} {% if
  not(nr == None) %}  <h2><img height="25"
src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{nr.Circuit.Location.country | replace(" ", "-")}}.png">&nbsp;  {{ nr.round }} :  {{ nr.raceName }}</h2>

  <small>Local time : {{ as_timestamp(nr.date + ' ' + nr.time) |
  timestamp_custom("%H:%M on %d-%m-%Y") }}</small>

  <a target="_new" href="{{nr.Circuit.url}}">
    <img width="100%" src="https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{nr.Circuit.Location.country | replace(" ","_")}}_Circuit.png.transform/7col/image.png">
  </a> <br> 
Season: {{nr.season}}<br>
Race nr: {{nr.round}}<br><br>
Race name : {{nr.raceName}}<br>
Circuit name : {{nr.Circuit.circuitName}}<br>
Location: {{nr.Circuit.Location.country}}<br><br>
Date :  {{ as_timestamp(nr.date ) | timestamp_custom("%d-%m-%y ") }} <br>
Track time : {{ nr.time }} 
 {{ as_timestamp(nr.time) | timestamp_custom("%H:%M") }}
<br>
{% endif %}
```

**Comment by huizebruin** [comment]
and this one for all races
```
type: markdown
content: |-
  <table>
    <thead>
      <tr>
        <th>&nbsp;</th>
        <th>Race</th>
        <th >Date</th>
      </tr>
    </thead>
    <tbody>
  {% for races in states.sensor.formula_one_sensor.attributes.races %} <tr>
          <td>{{races.round}}</td>
          <td>{{races.raceName}}</td>
          <td>{{races.date}}</td>
      </tr>
  {% endfor %}
    </tbody>
  </table>
card_mod:
  style:
    ha-markdown$: |
      table {
        width: 100%;
        border-spacing: 0;
        border-collapse: separate;
      }
      th {
        color: white;
        background: black;
      }
      tr:nth-child(even) {
        background-color: #dddddd;;
        color: rgb(33,33,33);
      }
      td:nth-child(1) {
        width: 50px;
        text-align: center;
      }
      td:nth-child(2) {
        text-align: left;
      }
      td:nth-child(3) {
        width: 60px;
        text-align: center;
      }
```

**Comment by mhoogenbosch** [comment]
mmm both don't work for me. 

![image](https://user-images.githubusercontent.com/36899598/167720894-5bd3abdb-03fe-4ea2-ab23-8ab0affcc040.png)
 
for the first

and

![image](https://user-images.githubusercontent.com/36899598/167720976-4df4f3a8-fe27-4517-9887-e70fe367eca6.png)

for the second.

**Comment by huizebruin** [comment]
the first i have this.
the last one i didn't had fixed yet.
![image](https://user-images.githubusercontent.com/62996429/167919635-d6e06940-df07-4b3d-adc7-483ad85e3939.png)
```
type: markdown
content: >2-
   {% set nr = states.sensor.formula_one_sensor.attributes.next_race  %} {% if
    not(nr == None) %}  <h2><img height="25"
  src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{nr.Circuit.Location.country
  | replace(" ", "-")}}.png">&nbsp;  {{ nr.round }} :  {{ nr.raceName }}</h2>

    <small>Local time : {{ as_timestamp(nr.date + ' ' + nr.time) |
    timestamp_custom("%H:%M on %d-%m-%Y") }}</small>

    <a target="_new" href="{{nr.Circuit.url}}">
      <img width="100%" src="https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{nr.Circuit.Location.country | replace(" ","_")}}_Circuit.png.transform/7col/image.png">
    </a> <br> 
  Season: {{nr.season}}<br>

  Race nr: {{nr.round}}<br><br>

  Race name : {{nr.raceName}}<br>

  Circuit name : {{nr.Circuit.circuitName}}<br>

  Location: {{nr.Circuit.Location.country}}<br><br>

  Date :  {{ as_timestamp(nr.date ) | timestamp_custom("%d-%m-%y ") }} <br>

  Track time : {{ nr.time }} 
   {{ as_timestamp(nr.time) | timestamp_custom("%H:%M") }}
  <br>

  {% endif %}
title: Next race
card_mod:
  style:
    ha-markdown$: |
      * {
        font-family: FormulaOne, "Titillium Web";
      }
```

and the second one i have this
![image](https://user-images.githubusercontent.com/62996429/167919791-225b1b30-4efb-4d6b-a4b5-2596484d267f.png)
```
type: markdown
content: |-
  <table>
    <thead>
      <tr>
        <th>&nbsp;</th>
        <th>Race</th>
        <th >Date</th>
      </tr>
    </thead>
    <tbody>
  {% for races in states.sensor.formula_one_sensor.attributes.races %} <tr>
          <td>{{races.round}}</td>
          <td>{{races.raceName}}</td>
          <td>{{races.date}}</td>
      </tr>
  {% endfor %}
    </tbody>
  </table>
card_mod:
  style:
    ha-markdown$: |
      table {
        width: 100%;
        border-spacing: 0;
        border-collapse: separate;
      }
      th {
        color: white;
        background: black;
      }
      tr:nth-child(even) {
        background-color: #dddddd;;
        color: rgb(33,33,33);
      }
      td:nth-child(1) {
        width: 50px;
        text-align: center;
      }
      td:nth-child(2) {
        text-align: left;
      }
      td:nth-child(3) {
        width: 60px;
        text-align: center;
      }
```

**Comment by mhoogenbosch** [comment]
My bad! Didn't change it in the RAW code, but in the visual editor. 

I'd really love to see the AIR time of the races. Now in your first picture there is a rewrite of the time / date. I can't seem to get that working for the race overview. Any thoughts here?

**Comment by delzear** [comment]
This is what I have configured on my Home Assistant Dashboard:
`
{% set nr = states.sensor.formula_one_sensor.attributes.next_race %} 
{% if not(nr == None)%} 
  {% set flag = nr.Circuit.Location.country | replace(" ","_") %} 
  {% set track = nr.Circuit.Location.country | replace(" ","_") %} 
  {% if (nr.Circuit.Location.country == "Bahrain") %} 
    {% set flag = "Bahrain" %}
    {% set track = nr.Circuit.Location.country %}
  {% endif %}
  {% if (nr.Circuit.Location.country == "UK") %} 
    {% set flag = "United-Kingdom" %}
    {% set track = "Great_Britain" %}
  {% endif %}
  {% if (nr.Circuit.Location.country == "Hungary") %} 
    {% set flag = "Hungary" %}  
    {% set track = nr.Circuit.Location.country %}
  {% endif %}
  {% if (nr.Circuit.Location.country == "Belgium") %} 
    {% set flag = "Belgium" %}  
    {% set track = nr.Circuit.Location.country %}
  {% endif %}
  {% if (nr.Circuit.Location.country == "Italy") %} 
    {% set flag = "Italy" %}  
    {% set track = "Emilia_Romagna" %}
  {% endif %}
  {% if (nr.Circuit.Location.country == "Russia") %} 
    {% set flag = "Russia" %}  
    {% set track = nr.Circuit.Location.country %}
  {% endif %}
  {% if (nr.Circuit.circuitId == "miami") %} 
    {% set flag = "United-States-of-America" %}  
    {% set track = nr.Circuit.Location.locality %}
  {% endif %}  
  {% if (nr.Circuit.circuitId == "americas") %} 
    {% set flag = "United-States-of-America" %}  
    {% set track = nr.Circuit.Location.country %}
  {% endif %}  
  {% if (nr.Circuit.Location.country == "Saudi Arabia") %} 
    {% set flag = "Saudi-Arabia" %}  
    {% set track = "Saudi_Arabia" %}
  {% endif %}
  {% if (nr.Circuit.Location.country == "UAE") %} 
    {% set flag = "United-Arab-Emirates" %}  
    {% set track = "Abu_Dhabi" %}
  {% endif %}
  {% if (nr.Circuit.Location.country == "Monaco") %} 
    {% set flag = "Monaco" %}  
    {% set track = "Monoco" %}
  {% endif %}
  {% if (nr.Circuit.Location.country == "Azerbaijan") %} 
    {% set flag = "Azerbaijan" %}  
    {% set track = "Baku" %}
  {% endif %}

  <h2>
    <img height="22" src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{flag}}.png">&nbsp;
    {{ nr.raceName }}
  </h2>
  <small> {{nr.Circuit.circuitName}} | {{ as_timestamp(nr.date + ' ' + nr.time) | timestamp_custom("%Y-%m-%d %H:%M") }}</small>
  <a target="_new" href="{{nr.Circuit.url}}">
    <img width="100%" src="https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{track}}_Circuit.png.transform/7col/image.png"></a>   
{% endif %}`

![image](https://user-images.githubusercontent.com/727891/167942541-81d3c049-0e3e-47bc-b4ea-d28df83d36bf.png)

**Comment by ostracizado** [comment]
Here's mine, if it helps:

```
type: markdown
content: >-
  {% set nr = states.sensor.formula_one_sensor.attributes.next_race  %} {% if
  not(nr == None) %}  <h2><img height="25"
  src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{nr.Circuit.Location.country}}.png">&nbsp; 
  {{ nr.round }} :  {{ nr.raceName }}</h2>

  <small>Local time : {{ as_timestamp(nr.date + ' ' + nr.time) |
  timestamp_custom("%H:%M on %y-%m-%D ") }}</small>

  <a target="_new" href="{{nr.Circuit.url}}">
    <img width="100%" src="https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{nr.Circuit.Location.country}}_Circuit.png.transform/7col/image.png">
  </a> <br> 

  Season: {{nr.season}}<br>

  Race: {{nr.round}}<br>

  Race name : {{nr.raceName}}<br>

  Circuit name : {{nr.Circuit.circuitName}}<br>

  Location: {{nr.Circuit.Location.country}}<br>

  Date : {{nr.date}}<br> {% endif %}
title: Next race
card_mod:
  style:
    ha-markdown$: |
      * {
        font-family: , "Titillium Web";
      }
```
![nextrace](https://user-images.githubusercontent.com/78053830/167966188-398e212f-5bcf-475b-93f8-41954c1af0a6.png)


```
type: markdown
content: |-
  <table>
    <thead>
      <tr>
        <th>&nbsp;</th>
        <th>Race</th>
        <th class="center">Date</th>
      </tr>
    </thead>
    <tbody>
  {% for races in states.sensor.formula_one_sensor.attributes.races %} <tr>
          <td>{{races.round}}</td>
          <td>{{races.raceName}}</td>
          <td>{{races.date}}</td>
      </tr>
  {% endfor %}
    </tbody>
  </table>
theme: M3-04-Magenta
card_mod:
  style:
    ha-markdown$: |
      table {
        width: 100%;
        border-spacing: 0;
        border-collapse: separate;
      }
      th {
        color: white;
        background: black;
      }
      tr:nth-child(even) {
        background-color: #dddddd;;
        color: rgb(33,33,33);
      }
      td:nth-child(1) {
        width: 50px;
        text-align: center;
      }
      td:nth-child(2) {
        text-align: center;
      }
      td:nth-child(3) {
        width: 80px;
        text-align: center;
      }
```
![allraces](https://user-images.githubusercontent.com/78053830/167966174-c6361057-a515-4ad7-b800-039640771f95.png)

I also think that the Google Calendar, with the F1 dates, is a quite a plus to have it side by side:

![calendar](https://user-images.githubusercontent.com/78053830/167966499-b0287a60-534a-4662-970e-87e9e7588105.png)

**Comment by delzear** [comment]
To display the data use the Formula One Card by marcokeeftl87.
https://github.com/marcokreeft87/formulaone-card
