### ISSUE TITLE
Different track map

### ISSUE THREAD

**Issue by skulumani** [delzear/hass-formulaoneapi#2]
Great integration for HA. 

Any ideas on how to utilize a different track map. I would like to use this one from Wikipedia 

https://en.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps#/media/File:Spa-Francorchamps_of_Belgium.svg

As it's nice having the corner names/numbers available. I don't think the URLs are as nicely formatted where one can use the sensor attributes like in your example. 

Is it possible to include the images in your integration directly? Or some other approach?

Thanks

**Comment by skulumani** [comment]
Here's another link that can be used. Not sure if there's a good way to see all the options available on the FOM website

~~~
https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{nr.Circuit.Location.country}}_Circuit.png.transform/7col/image.png
~~~

looks like this for spa

![image](https://user-images.githubusercontent.com/5266022/130245219-b368e18b-77b6-4925-97b9-2477d899a65e.png)

**Comment by Creativesz** [comment]
The images for the track and flag are not working for Saudi Arabia.
Just installed the plugin and set-up the frontend, so i'm not sure if this is my config (just copy/paste) or a error with the circuit name and image filename.

**Comment by austensmith** [comment]
This fixes that.

` {% set nr = states.sensor.formula_one.attributes.next_race  %} {% if
  not(nr == None) %}  <h2><img height="25"
  src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{nr.Circuit.Location.country | replace(" ", "-")}}.png">&nbsp; 
  {{ nr.round }} :  {{ nr.raceName }}</h2>

  <small>Local time : {{ as_timestamp(nr.date + ' ' + nr.time) |
  timestamp_custom("%H:%M on %y-%m-%D ") }}</small>

  <a target="_new" href="{{nr.Circuit.url}}">
    <img width="100%" src="https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{nr.Circuit.Location.country | replace(" ","_")}}_Circuit.png.transform/7col/image.png">
  </a> <br> 

  Season: {{nr.season}}<br>

  Race: {{nr.round}}<br>

  Race name : {{nr.raceName}}<br>

  Circuit name : {{nr.Circuit.circuitName}}<br>

  Location: {{nr.Circuit.Location.country}}<br>

  Date : {{nr.date}}<br>

  Time : {{nr.time}}<br>  {% endif %}
`

**Comment by LRvdLinden** [comment]
> {% set nr = states.sensor.formula_one.attributes.next_race  %} {% if
>   not(nr == None) %}  <h2><img height="25"
>   src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{nr.Circuit.Location.country | replace(" ", "-")}}.png">&nbsp; 
>   {{ nr.round }} :  {{ nr.raceName }}</h2>
> 
>   <small>Local time : {{ as_timestamp(nr.date + ' ' + nr.time) |
>   timestamp_custom("%H:%M on %y-%m-%D ") }}</small>
> 
>   <a target="_new" href="{{nr.Circuit.url}}">
>     <img width="100%" src="https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{nr.Circuit.Location.country | replace(" ","_")}}_Circuit.png.transform/7col/image.png">
>   </a> <br>

can you share the whole markdown?

**Comment by austensmith** [comment]
I've just updated the code, I missed the sensor from it.
![image](https://user-images.githubusercontent.com/66824771/159175225-9ac776e1-bb26-4315-acf9-6e9b7462e7ed.png)
