### ISSUE TITLE
Next race shows next race instead of upcoming race

### ISSUE THREAD

**Issue by davidrustingha** [delzear/hass-formulaoneapi#21]
Right now it's sunday and the race hasn't begun yet. It still shows the next race being on the Jeddah Circuit.

**Comment by evildonkey1** [comment]
Same here, and im not seeing the png's

**Comment by robinwillems** [comment]
I have the same problem. Next race instead of today and no images

**Comment by austensmith** [comment]
This fixes the image and logos. Both couldn't account for spaces.

```
 {% set nr = states.sensor.formula_one.attributes.next_race  %} {% if
  not(nr == None) %}  <h2><img height="25"
  src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{nr.Circuit.Location.country | replace(" ", "-")}}.png">&nbsp; 
  {{ nr.round }} :  {{ nr.raceName }}</h2>

  <small>Local time : {{ as_timestamp(nr.date + ' ' + nr.time) |
  timestamp_custom("%H:%M on %y-%m-%D ") }}</small>

  <a target="_new" href="{{nr.Circuit.url}}">
    <img width="100%" src="https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{nr.Circuit.Location.country | replace(" ","_")}}_Circuit.png.transform/7col/image.png">
  </a> <br> 

  Season: {{nr.season}}<br>

  Race: {{nr.round}}<br>

  Race name : {{nr.raceName}}<br>

  Circuit name : {{nr.Circuit.circuitName}}<br>

  Location: {{nr.Circuit.Location.country}}<br>

  Date : {{nr.date}}<br>

  Time : {{nr.time}}<br>  {% endif %}

```

**Comment by robinwillems** [comment]
> {% set nr = states.sensor.formula_one_sensor.attributes.next_race  %} {% if
>   not(nr == None) %}  <h2><img height="25"
>   src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{nr.Circuit.Location.country | replace(" ", "-")}}.png">&nbsp; 
>   {{ nr.round }} :  {{ nr.raceName }}</h2>
> 
>   <small>Local time : {{ as_timestamp(nr.date + ' ' + nr.time) |
>   timestamp_custom("%H:%M on %y-%m-%D ") }}</small>
> 
>   <a target="_new" href="{{nr.Circuit.url}}">
>     <img width="100%" src="https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{nr.Circuit.Location.country | replace(" ","_")}}_Circuit.png.transform/7col/image.png">
>   </a> <br>

Yes, this works perfectly for the images problem

**Comment by evildonkey1** [comment]
Works like a charm. Thnx
