### ISSUE TITLE
Circuit Image Now Showing 

### ISSUE THREAD

**Issue by geroulas** [delzear/hass-formulaoneapi#23]
For anyone having problem with Circuit png not showing.
When country: Saudi Arabia, has 2 words you need to add `|replace(' ','_')` after `{{nr.Circuit.Location.country` in your Markdown card.

`<img width="100%" src="https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{nr.Circuit.Location.country|replace(' ','_')}}_Circuit.png.transform/7col/image.png">`

**Comment by freggel2** [comment]
> For anyone having problem with Circuit png not showing. When country: Saudi Arabia, has 2 words you need to add `|replace(' ','_')` after `{{nr.Circuit.Location.country` in your Markdown card.
> 
> `<img width="100%" src="https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{nr.Circuit.Location.country|replace(' ','_')}}_Circuit.png.transform/7col/image.png">`

@geroulas when I put this code in the markdown card it shows nothing. Is there something I did wrong? Could you please push me in the right direction?
I've put the code in the UI card configuration. And when I save it it won't show the picture.
When I put this img (for example this picture: https://media.nu.nl/m/x34xcs7asctr_wd1280.jpg/geen-auteursrecht-dieren-uitspraak-rechter-vs-in-zaak-selfie-aap.jpg) the image will show.
