### ISSUE TITLE
track image url not correct

### ISSUE THREAD

**Issue by aaamoeder** [delzear/hass-formulaoneapi#28]
The track image url that gets used looks to the attribute "Circuit.Location.country" but the images on the source site are not labelled that way.

eg: current GP in italy gets the url 
"https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Italy_Circuit.png.transform/7col/image.png"

while it should be 
"https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Emilia_Romagna_Circuit.png.transform/7col/image.png"

I can't find the correct name anywhere in the attributs so not sure how to fix this myself.

If you could look into this, that would be great ! thanks !

**Comment by DeadpoolW** [comment]
Same for current race, the attribute "Circuit.Location.country" generates USA which results in the COTA circuit.

this is generated:
[https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/USA_Circuit.png.transform/9col/image.png](url)

while it should be:
[https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Miami_Circuit.png.transform/9col/image.png](url)

Is it possible to have the links of the tracks in the attributes?

**Comment by delzear** [comment]
For now, no! My server is only redirecting the API from Ergast with a caching mechanism. I need to look into it but for now it is simply an integration and not a frontend component.

**Comment by ice413** [comment]
I just noticed there's a typo at formula1.com for Monaco.
The circuit-image name there is "monoco" not "monaco"
I solved it in the MD-card with: {{nr.Circuit.Location.country | replace("Monaco","Monoco") | replace(" ","_")}}

Same thing with Azerbaijan
Needed to add:
replace("Azerbaijan","Baku")

**Comment by mhoogenbosch** [comment]
> replace("Azerbaijan","Baku")

mmm... can't seem to get it to work. It stays a not working image.

When hoovering over the image it shows: [](https://en.wikipedia.org/wiki/Baku_City_Circuit)

I now have replaced: 

`{{nr.Circuit.Location.country }}`

with:

` {{nr.Circuit.Location.country | replace("Monaco","Monoco") | replace(" ","_") | replace("Azerbaijan","Baku") }}`

**Comment by Waylikemark** [comment]
> > replace("Azerbaijan","Baku")
> 
> mmm... can't seem to get it to work. It stays a not working image.
> 
> When hoovering over the image it shows:
> 
> I now have replaced:
> 
> `{{nr.Circuit.Location.country }}`
> 
> with:
> 
> ` {{nr.Circuit.Location.country | replace("Monaco","Monoco") | replace(" ","_") | replace("Azerbaijan","Baku") }}`

replace(" ","_") should come last. So it needs to be: {{nr.Circuit.Location.country | replace("Monaco","Monoco") | replace("Azerbaijan","Baku") | replace(" ","_") }}

**Comment by HA-TB303** [comment]
Could someone please post a working lovelace card? I have tried to make to above change, but the Baku card is still not showing.

Thanks!

**Comment by mhoogenbosch** [comment]
> Could someone please post a working lovelace card? I have tried to make to above change, but the Baku card is still not showing.
> 
> Thanks!

```
{% set nr = states.sensor.formula_one_sensor.attributes.next_race  %} {% if not(nr == None) %}  <h2><img height="25" src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{nr.Circuit.Location.country | replace(" ","-")}}.png">&nbsp;  {{ nr.round }} :  {{ nr.raceName }}</h2>
<small>Local time : {{ as_timestamp(nr.date + ' ' + nr.time) | timestamp_custom("%H:%M on %d-%m-%y ") }}</small>
<a target="_new" href="{{nr.Circuit.url}}">
  <img width="100%" src="https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{nr.Circuit.Location.country | replace("Monaco","Monoco") | replace("Azerbaijan","Baku") | replace(" ","") }}_Circuit.png.transform/7col/image.png">
</a> <br> 
Season: {{nr.season}}<br>
Race: {{nr.round}}<br><br>
Race name : {{nr.raceName}}<br>
Circuit name : {{nr.Circuit.circuitName}}<br><br>
Location:  {{nr.Circuit.Location.country | replace("Monaco","Monoco") | replace(" ","_") | replace("Azerbaijan","Baku") }}<br>
Date : {{nr.date}}<br>
Time : {{nr.time}}<br>
TV Time : {{ as_timestamp(nr.date + ' ' + nr.time) | timestamp_custom("%H:%M") }}<br>{% endif %}
```

**Comment by HA-TB303** [comment]
HIi,
 thanks for sharing , but could you please post again in code tags (```) as this is not usable.

Thanks!

**Comment by mhoogenbosch** [comment]
it is in code tags..

**Comment by HA-TB303** [comment]
It's not a lovelace card, it juts a fragment of it. I can't get this to work either.

Thanks anyway.

**Comment by mhoogenbosch** [comment]
```
type: markdown
content: >-
  {% set nr = states.sensor.formula_one_sensor.attributes.next_race  %} {% if
  not(nr == None) %}  <h2><img height="25"
  src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{nr.Circuit.Location.country
  | replace(" ","-")}}.png">&nbsp;  {{ nr.round }} :  {{ nr.raceName }}</h2>

  <small>Local time : {{ as_timestamp(nr.date + ' ' + nr.time) |
  timestamp_custom("%H:%M on %d-%m-%y ") }}</small>

  <a target="_new" href="{{nr.Circuit.url}}">
    <img width="100%" src="https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{nr.Circuit.Location.country | replace("Monaco","Monoco") | replace("Azerbaijan","Baku") | replace(" ","") }}_Circuit.png.transform/7col/image.png">
  </a> <br> 

  Season: {{nr.season}}<br>

  Race: {{nr.round}}<br><br>

  Race name : {{nr.raceName}}<br>

  Circuit name : {{nr.Circuit.circuitName}}<br><br>

  Location:  {{nr.Circuit.Location.country | replace("Monaco","Monoco") |
  replace(" ","_") | replace("Azerbaijan","Baku") }}<br>

  Date : {{nr.date}}<br>

  Time : {{nr.time}}<br>

  TV Time : {{ as_timestamp(nr.date + ' ' + nr.time) | timestamp_custom("%H:%M")
  }}<br>{% endif %}
title: Next race
card_mod:
  style:
    ha-markdown$: |
      * {
        font-family: FormulaOne, "Titillium Web";
      }

```

**Comment by HA-TB303** [comment]
Yes this works. Thank you!

<img width="510" alt="image" src="https://user-images.githubusercontent.com/9609805/172049450-e34c875b-41af-4de3-984e-18faca5ab845.png">

**Comment by DennisDav774** [comment]
https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{nr.Circuit.Location.country | replace("Azerbaijan","Baku") | replace("UK","Great_Britain")| replace(" ","_")}}_Circuit.png.transform/7col/image.png

**Comment by mhoogenbosch** [comment]
Anyone else also missing the flag picture of UK?
