### ISSUE TITLE
Next race section there is an error in the date 

### ISSUE THREAD

**Issue by mhoogenbosch** [delzear/hass-formulaoneapi#30]
<small>Local time : {{ as_timestamp(nr.date + ' ' + nr.time) | timestamp_custom("%H:%M on %d-%m-%y ") }}</small>

You are using a capital D which makes a double date.

**Comment by delzear** [comment]
This is not an error, it is the standard in my country.

**Comment by mhoogenbosch** [comment]
It showed 22-05-22/05/22 here. So I figured it had to be a bug. But solved, thanks!
