### ISSUE TITLE
Max verstappen carnumber still 33

### ISSUE THREAD

**Issue by mhoogenbosch** [delzear/hass-formulaoneapi#31]
The car number of max has changed to 1 this year. This isn't reflected by the list.  Is this a static number?

**Comment by huizebruin** [comment]
Because this addon getting his information from this site.
[http://ergast.com/mrd/](http://ergast.com/mrd/
)
and max his Permanent Number is 33
[http://ergast.com/api/f1/2022/drivers](http://ergast.com/api/f1/2022/drivers
)

**Comment by mhoogenbosch** [comment]
Nothing to do about it then, i'll close the issue.

**Comment by EvertJob** [comment]
@huizebruin maybe it's possible to get the information from last year: http://ergast.com/api/f1/2021/driverStandings

@mhoogenbosch I've changed the line:
`<td> {% if (driver.Driver.permanentNumber == '33')%}1{%else%}{{driver.Driver.permanentNumber}}{%endif%}</td>`
Just change the permanent number from the campion previous year ;)
