### ISSUE TITLE
next race refresh to soon.

### ISSUE THREAD

**Issue by GHeiner** [delzear/hass-formulaoneapi#34]
Today 10-07 the next_race is already the race for 24-07 (France) , but the current race on 10-07 (Austria) is still on. I think the next race has te change on the day after the current race.

This is what I see now on 10-07:
next_race:
  season: '2022'
  round: '12'
  url: http://en.wikipedia.org/wiki/2022_French_Grand_Prix
  raceName: French Grand Prix
  Circuit:
    circuitId: ricard
    url: http://en.wikipedia.org/wiki/Paul_Ricard_Circuit
    circuitName: Circuit Paul Ricard
    Location:
      lat: '43.2506'
      long: '5.79167'
      locality: Le Castellet
      country: France
  date: '2022-07-24'
  time: 13:00:00Z
  FirstPractice:
    date: '2022-07-22'
    time: 12:00:00Z
  SecondPractice:
    date: '2022-07-22'
    time: 15:00:00Z
  ThirdPractice:
    date: '2022-07-23'
    time: 11:00:00Z
  Qualifying:
    date: '2022-07-23'
    time: 14:00:00Z
races:

**Comment by marc115uk** [comment]
Same has happened with todays race over 19hrs prior to COTA race running already showing Mexico as next race

**Comment by marcokreeft87** [comment]
https://github.com/delzear/hass-formulaoneapi/pull/55 This fixed it on my HA waiting for @delzear  to approve

**Comment by BebeMischa** [comment]
fixed here too ;-)
