### ISSUE TITLE
unknown

### ISSUE THREAD

**Issue by schumi2309** [delzear/hass-formulaoneapi#35]
hello. My API is not working. is there something to do, I have my sensor but it puts me unknown ?

**Comment by nautiqu3** [comment]
Same here. It was working last night but today it just says unknown. 
Seems like it cannot connect to host when checking my logs.

**Comment by schumi2309** [comment]
ok thank you to you, it reassures me that I am not the only one.

**Comment by bpel86** [comment]
Same here!

**Comment by delzear** [comment]
Sorry, but I'm not standing on my phone! My server went down this morning!
I will check when I will get home tonight

**Comment by schumi2309** [comment]
Ok, thanks...

**Comment by EvertJob** [comment]
@delzear what do you need for a backup server? Maybe I could help you with it?

**Comment by delzear** [comment]
It is simple asp.net core webserver. Should be able to work on a Windows or
Linux Server

**Comment by delzear** [comment]
Server is back online. My virtual host died!!! This is going to cost me loads of money!

**Comment by EvertJob** [comment]
How is this cost you loads of money? Virtual hosts are not that expensive? :)

**Comment by schumi2309** [comment]
Still nothing at home, is that normal?

**Comment by EvertJob** [comment]
> Still nothing at home, is that normal?

Try a reboot

**Comment by nautiqu3** [comment]
Working fine for me :)

**Comment by schumi2309** [comment]
All right, all it's ok after reboot. thanks my friends...

**Comment by delzear** [comment]
@EvertJob Because I own the server, I had to rent a server to host. But I have to buy a new one!

**Comment by EvertJob** [comment]
> @EvertJob Because I own the server, I had to rent a server to host. But I have to buy a new one!

@delzear maybe we could by you a coffee ;)?

**Comment by delzear** [comment]
@EvertJob Buy me coffee link is now in the readme file

**Comment by EvertJob** [comment]
Done. @schumi2309 @nautiqu3 @bpel86 buy this guy some coffee! https://www.buymeacoffee.com/delzear

**Comment by schumi2309** [comment]
hello, the api is not working again.

**Comment by schumi2309** [comment]
it's ok.

**Comment by delzear** [comment]
Yes, I forgot to set a static IP on my new server!!!

*David Audet*
