### ISSUE TITLE
Integration error

### ISSUE THREAD

**Issue by chuddnutts** [delzear/hass-formulaoneapi#37]
I have just tried to set this integration up and get the following error

> 
> This error originated from a custom integration.
> 
> Logger: homeassistant.helpers.entity
> Source: custom_components/formulaone_api/sensor.py:70
> Integration: formulaone_api (documentation)
> First occurred: 23:06:20 (1 occurrences)
> Last logged: 23:06:20
> 
> Update for sensor.formula_one_sensor fails
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
>     raise err
>   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
>     sock.connect(sa)
> OSError: [Errno 113] Host is unreachable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
>     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
>   File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
>     self.send(msg)
>   File "/usr/local/lib/python3.10/http/client.py", line 975, in send
>     self.connect()
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
>     conn = self._new_conn()
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xad0475b0>: Failed to establish a new connection: [Errno 113] Host is unreachable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
>     resp = conn.urlopen(
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
>     retries = retries.increment(
>   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ergastcache.mobiusmedia.ca', port=80): Max retries exceeded with url: /f1/current.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xad0475b0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
>     await self.async_device_update()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
>     raise exc
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/formulaone_api/sensor.py", line 239, in update
>     self.set_state()
>   File "/config/custom_components/formulaone_api/sensor.py", line 218, in set_state
>     all_attr = self.get_race_data()
>   File "/config/custom_components/formulaone_api/sensor.py", line 189, in get_race_data
>     races = f1.current_schedule().json
>   File "/config/custom_components/formulaone_api/sensor.py", line 81, in json
>     self._json = self.make_request(".json")
>   File "/config/custom_components/formulaone_api/sensor.py", line 70, in make_request
>     return requests.get(self.url, params=querystring)
>   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
>     return request("get", url, params=params, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='ergastcache.mobiusmedia.ca', port=80): Max retries exceeded with url: /f1/current.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xad0475b0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

Would you know why?

**Comment by chuddnutts** [comment]
Sorry I have seen others lsp have the same issue and you have said the server is down. I will wait.

**Comment by delzear** [comment]
Server is back online. My virtual host died!!! This is going to cost me loads of money!
