### ISSUE TITLE
qualifying

### ISSUE THREAD

**Issue by EvertJob** [delzear/hass-formulaoneapi#38]
Is it possible to get the qualifying and sprint qualifying information into the sensor?

**Comment by delzear** [comment]
@EvertJob It's already there, you just need to make markdown card for it. I don't have an example for it but I will try to make one.

**Comment by EvertJob** [comment]
Sorry, I ment the quali result :)

**Comment by delzear** [comment]
I will check if Ergast has the API, if not I don't think I will be able to do it!
