### ISSUE TITLE
Error log Lovelace card

### ISSUE THREAD

**Issue by Jurgenn22** [delzear/hass-formulaoneapi#4]
Am I the only one getting a log error based on the input to the Lovelace card? 
Error:
ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{% set nr = states.sensor.formula_one_sensor.attributes.next_race %} {% if not(nr == None) %} <h1><img height="22" src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{nr.Circuit.Location.country}}.png">&nbsp; {{ nr.raceName }}</h1>

Can you help me please?

**Comment by delzear** [comment]
Use the Formula One Card by marcokeeftl87.
https://github.com/marcokreeft87/formulaone-card
