### ISSUE TITLE
formula_one_sensor_last_result

### ISSUE THREAD

**Issue by EvertJob** [delzear/hass-formulaoneapi#44]
When I'm using:
```
{% for results in states.sensor.formula_one_sensor_last_result.attributes.data %} <tr>
        <td><b>{{results.number}}</b></td>
        <td>{{results.driverId}}</td>
        <td>{{results.position}}</td>
        <td>{{results.points}}</td>
    </tr>
{% endfor %}
  </tbody>
</table>
```

The result is: `UndefinedError: 'str object' has no attribute 'number'`

Anyone with a solution?

**Comment by marcokreeft87** [comment]
You need to use for results in states.sensor.formula_one_sensor_last_result.attributes.data.Results

**Comment by marcokreeft87** [comment]
PS. If you dont want to use markdown templates. There is a new way of displaying the data: 

https://github.com/marcokreeft87/formulaone-card

**Comment by EvertJob** [comment]
> PS. If you dont want to use markdown templates. There is a new way of displaying the data:
> 
> https://github.com/marcokreeft87/formulaone-card

Great card! Thanks!
