### ISSUE TITLE
Flag of USA not working in "Next Race" Lovelace card

### ISSUE THREAD

**Issue by thewolf-oz** [delzear/hass-formulaoneapi#48]
Great work! Have just added this through HACS

One point of note is the country returned for US GP is "USA" while Countries of the World use "United-States-of-America" is used in the image URL

I've injected an extra IF statement to allow for this:

  {% set nr = states.sensor.formula_one_sensor_races.attributes.next_race  %} {%
  if not(nr == None) %}
    {% if nr.Circuit.Location.country == "USA" %}
      <h2><img height="25" src="https://www.countries-ofthe-world.com/flags-normal/flag-of-United-States-of-America.png">&nbsp;  {{ nr.round }} :  {{ nr.raceName }}</h2>
    {% else %}
      <h2><img height="25" src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{nr.Circuit.Location.country | replace(" ","-")}}.png">&nbsp;  {{ nr.round }} :  {{ nr.raceName }}</h2>
    {% endif %}

**Comment by marcokreeft87** [comment]
Thnx for the headsup. Ive put this in the card we have https://github.com/marcokreeft87/formulaone-card. I think at a certain point we need to stop with support on the markdown because its not part of the integration
