### ISSUE TITLE
API ?

### ISSUE THREAD

**Issue by schumi2309** [delzear/hass-formulaoneapi#49]
Hello,
Have you a problem with your api ? 
I do not have anything !
Thanks...

**Comment by marcokreeft87** [comment]
What are you trying to ask @schumi2309 ? The api is working for me. If its not working, plz check your HA logs

**Comment by schumi2309** [comment]
nothing in my log

**Comment by schumi2309** [comment]
it's ok.
I copied the card, and it works.
Weird !
