### ISSUE TITLE
Flag of USA doesn't show as flag API doesn't accept USA as value

### ISSUE THREAD

**Issue by WvanWaas** [delzear/hass-formulaoneapi#53]
Flag API wants United States of America and most flag API's would expect US 
Sensor gives USA probably it's better to show country code as ISO 3166-1 alpha-2

**Comment by WvanWaas** [comment]
appologies I see you already closed the issue in another situation. The question wasn't for markdown but more for a standard country code output.

**Comment by marcokreeft87** [comment]
The API just passes the country in which the race is taking place. The markdown is just an extra. Maybe we will take this with an future update but don't count on it happening in the near future. But for now either take the solution in the other issue or use the formulaone-card card to display the data, this will fix the issues for you
