### ISSUE TITLE
API ?

### ISSUE THREAD

**Issue by schumi2309** [delzear/hass-formulaoneapi#60]
Hello,
Have you a problem with your API ?
I do not have anything.

**Comment by jey-music** [comment]
Hi,
I have the same problem atm.
Sensor states are all on "Unknown".
Thx

**Comment by mfabiani53** [comment]
Yes, i confirm it. Just installed and nothing in the card, only tons of errors in the log....

**Comment by marcokreeft87** [comment]
I get data back from the sensor..  weird..

**Comment by delzear** [comment]
Ergast is having problems with his server. My cache server is running correctly. Unfortunatly, Ergast does not have, at this moment, any health monitoring. He is looking into it.

**Comment by schumi2309** [comment]
Me too. it's good.
