### ISSUE TITLE
entity does not have a unique ID

### ISSUE THREAD

**Issue by Santanachia** [delzear/hass-formulaoneapi#61]
This entity ('sensor.formula_one_sensor_last_result') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.

**Comment by delzear** [comment]
This is not a error. If you look at the documentation link, it is written that it can stay like that

**Comment by Santanachia** [comment]
it can be, but should it be?  What is the reason to prevent the sensor from being hidden in the GUI, or to prevent its icon from being changed?
