### ISSUE TITLE
Contact about your server message

### ISSUE THREAD

**Issue by adekloet** [delzear/hass-formulaoneapi#76]
Hi,

I would like to see how I (we) can help you out running the server (I have mailed Marco Kreeft of the f1 card to). Can you drop me a message how I could reach you to see what can be done on the short and long term? Maybe we can make the server distributed or get another solution in place.

Thanks and all the best!
Alex

**Comment by adekloet** [comment]
I see we can run our own ergast API server, which clones the ergast DB on it. I have found this github with a docker container which supposedly sets up an ergast API server: https://github.com/jcnewell/ergast-f1-api . It does seem a few years old and has outstanding issue's on it, so I am reluctant to install a server using this image. Maybe in a private message (email) we can discuss this to see if I can use your image or discuss install instructions so we could f.i. loadshare or find another way of doing this.

**Comment by delzear** [comment]
The fornula one card does get the data by it self now. So this integration is not needed anymore!

**Comment by adekloet** [comment]
Right, got a docker image from https://github.com/Edivad99/NJS-ErgastF1API running locally to test. So I have the Ergast API exposed on my local machine for testing. API is running on port 8080, but no data yet, maybe it needs some time to replicate from the main server. As I understand now your HA integration pulls it's data dfrom your Ergast API instance at: 

`    def _build_url(self, path, **kwargs) -> str:
        url = "{protocol}://ergastcache.mobiusmedia.ca/f1/{path}".format(
            protocol="http" if self.secure else "http", path=path.format(**kwargs)
        )
        return url`
So the http://ergastcache.mobiusmedia.ca/f1 get's overloaded with API request from the HA HACS integration installs and that needs to change. So we need to deploy a server to replace this or create some logic to load balance or something. Maybe we could give a "smart" user the ability to put in his own Ergast API URL...

**Comment by adekloet** [comment]
> The fornula one card does get the data by it self now. So this integration is not needed anymore!

Aha! So the card does the API lookup... wouldn't that not run into the same issue's, or the card get's the data from the ergast source?

**Comment by delzear** [comment]
I don't manage the card, Marco Kreeft does.
